-- CreateTable
CREATE TABLE "Colorway" (
    "slug" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "tier" TEXT NOT NULL,
    "dropNumber" INTEGER,
    "totalPieces" INTEGER,
    "piecesRemaining" INTEGER,
    "images" TEXT NOT NULL DEFAULT '[]',
    "matchedCarMake" TEXT,
    "matchedCarModel" TEXT,
    "matchedCarColorName" TEXT,
    "matchedCarImageUrl" TEXT,
    "matchedCarOwnerNote" TEXT,
    "story" TEXT,
    "whyPoints" TEXT NOT NULL DEFAULT '[]',
    "campaignQuote" TEXT,
    "campaignName" TEXT,
    "campaignRole" TEXT,
    "availabilityStatus" TEXT NOT NULL DEFAULT 'available',
    "availabilityShipsFrom" TEXT,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "launchedAt" TEXT NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
